---
- name: MariaDB
  tags: ["mariadb"]
  vars: 
    MARIADB_DATA_DIR: "{{DATA_DIR}}/mariadb"
  block: 
    - name: Create MariaDB network
      docker_network:
        name: mariadb

    - name: Create MariaDB data directory
      file:
        path: "{{ MARIADB_DATA_DIR }}"
        state: directory
        owner: 999
        group: 999
        mode: '0755'

    - name: Add MariaDB container
      docker_container:
        name: mariadb
        image: mariadb:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: mariadb
        ports: 
          - "127.0.0.1:3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
        volumes:
          - "{{ MARIADB_DATA_DIR }}:/var/lib/mysql"