- name: MongoDB
  tags: ["mongodb"]
  vars:
    MONGO_DATA_DIR: "{{ DB_DIR }}/mongodb"
  block:
    - name: Add MongoDB package to pip
      pip: 
        name: pymongo>4.0
        break_system_packages: true 

    - name: Create MongoDB network
      docker_network:
        name: mongodb

    - name: Create MongoDB data directory
      file:
        path: "{{ MONGO_DATA_DIR }}"
        state: directory
        owner: 999
        group: 999
        mode: '0755'

    - name: Run MongoDB container
      docker_container:
        name: mongodb
        image: mongo:latest
        state: started
        restart_policy: unless-stopped
        ports: 
          - "127.0.0.1:27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: "{{ MONGO_ROOT_USER }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ MONGO_ROOT_PASS }}"
        volumes:
          - "{{ MONGO_DATA_DIR }}:/data/db"
        networks:
          - name: mongodb
