---
- name: Grafana
  tags: ["grafana"]
  vars:
    GRAFANA_DATA_DIR: "{{ DATA_DIR }}/grafana"
  block:
    - name: Create Grafana data directory
      file:
        path: "{{ GRAFANA_DATA_DIR }}"
        state: directory
        owner: 472
        group: 472
        mode: '0755'

    - name: Add Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: traefik
          - name: loki
        volumes:
          - "{{ GRAFANA_DATA_DIR }}:/var/lib/grafana"
        env: 
          GF_SECURITY_ADMIN_USER: "{{ GRAFANA_USER }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ GRAFANA_PASS }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.grafana.rule: "Host(`dash.{{ BACKEND_DOMAIN }}`)"
          traefik.http.routers.grafana.entrypoints: "websecure"
          traefik.http.services.grafana.loadbalancer.server.port: "3000"