# TODO: Update to pull directory as list and loop
# TODO: Push backup to s3 
# TODO: Only keep 3 most recent backups on system
# TODO: Def not working lol
---
- name: Backup '/srv' directory
  tags: ["timezone"]
  vars: 
    dir_name: "backup-{{ ansible_date_time.date }}"
  block:
    - name: Copy to temp with Rsync
      ansible.builtin.copy:
        src: /srv
        dest: "/tmp/{{dir_name}}"

    - name: Compress backup and remove
      community.general.archive:
        path: "/tmp/{{dir_name}}"
        remove: true