# Update host
- import_tasks: ../../util/update.yml

# Backup host
- import_tasks: backup.yml

- name: Run JournalCTL Vacuum
  ansible.builtin.command: journalctl --vacuum-size 10M

- name: Run Docker System Prune
  ansible.builtin.command: docker system prune -f

# Reboot Host
- import_tasks: ../../util/reboot.yml

- name: Send a message to the Discord channel
  community.general.discord:
    webhook_id: "{{ DEPLOY_WEBHOOK_ID }}"
    webhook_token: "{{ DEPLOY_WEBHOOK_TOKEN }}"
    content: "Host {{ inventory_hostname }} has passed weekly checkin"
