---
- name: Grafana Setup
  tags: ["grafana"]
  block:

  - name: Add Grafana Helm repo
    kubernetes.core.helm_repository:
      name: grafana
      repo_url: https://grafana.github.io/helm-charts
      repo_state: present

  - name: Deploy Grafana
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: "{{ NAMESPACE }}"
      release_state: present
      wait: true
      values:
        persistence:
          enabled: true
          storageClassName: longhorn-retain
          accessModes:
            - ReadWriteOnce
          size: 5Gi
        adminPassword: "{{ GRAFANA_ADMIN_PASSWORD }}"
    environment:
      KUBECONFIG: "{{ KUBECONFIG }}"
