- name: Loki + MinIO Integration
  tags: ["loki"]
  block:
  - name: Download mc binary
    get_url:
      url: https://dl.min.io/client/mc/release/linux-amd64/mc
      dest: /usr/local/bin/mc
      mode: '0755'
  - name: Create Loki bucket in MinIO
    ansible.builtin.shell: |
      mc alias set localminio http://minio.STORAGE.svc.cluster.local:9000 {{ MINIO_ACCESS_KEY }} {{ MINIO_SECRET_KEY }}
      mc mb --ignore-existing localminio/{{ LOKI_BUCKETNAME }}
    environment:
      MC_HOST_localminio: "http://{{ MINIO_ACCESS_KEY }}:{{ MINIO_SECRET_KEY }}@minio.STORAGE.svc.cluster.local:9000"

  - name: Add Grafana Helm repo
    kubernetes.core.helm_repository:
      name: grafana
      repo_url: https://grafana.github.io/helm-charts
      repo_state: present

  - name: Copy Loki values
    ansible.builtin.template:
      src: loki.yml.j2
      dest: /var/manifests/loki.yaml

  - name: Deploy Loki (pointing to MinIO in STORAGE namespace)
    kubernetes.core.helm:
      name: loki
      chart_ref: grafana/loki
      release_namespace: "{{ NAMESPACE }}"
      release_state: present
      values_files: /var/manifests/loki.yaml
      wait: true
    environment:
      KUBECONFIG: "{{ KUBECONFIG }}"
