- name: Setup k3s 
  tags: ["k3s-setup"]
  block: 
    - import_tasks: helm.yml 

    - import_tasks: firewall.yml 

    - name: Install Ansible Python dep 
      apt: 
        name: 
          - python3-kubernetes

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh

    - name: Create a directory for manifests
      ansible.builtin.file:
        path: /var/manifests
        state: directory

    # Set the master node
    - name: Set variable for the first host based on the ENVIRONMENT variable
      set_fact:
        first_host: "{{ groups[ENVIRONMENT] | first }}"
      run_once: true  

    - name: Set KUBERNETES_MASTER to true for the first host
      set_fact:
        KUBERNETES_MASTER: "true"
      when: inventory_hostname == first_host

    - name: Display the first host
      debug:
        msg: "The first host in the {{ ENVIRONMENT }} group is: {{ first_host }}"
      when: inventory_hostname == first_host

- name: Setup master node
  tags: ["master-setup"]
  when: KUBERNETES_MASTER
  block:
    - name: Set Join IP for the first host 
      set_fact: 
        KUBERNETES_IP: "{{ ansible_default_ipv4.address }}"
        
    - name: Install as Master
      command: sh /tmp/k3s-install.sh server --cluster-init --tls-san={{ KUBERNETES_IP }} --disable=traefik
      environment: 
        K3S_TOKEN: "{{ K3S_TOKEN }}"

- name: Setup agent node 
  tags: ["agent-setup"]
  when: not KUBERNETES_MASTER
  block:
    - name: Install as Agent
      command: sh /tmp/k3s-install.sh server --cluster-init --server https://{{ hostvars[groups[ENVIRONMENT][0]]['KUBERNETES_IP'] }}:6443 --tls-san={{ hostvars[groups[ENVIRONMENT][0]]['KUBERNETES_IP'] }} --disable=traefik --disable=servicelb 
      environment: 
        K3S_TOKEN: "{{ K3S_TOKEN }}"
