---
- name: Docker Install
  hosts: dev
  become: true
  any_errors_fatal: true
  vars: 
    reboot: true
    STATE: "present"
  roles: 
    - configure
    - deploy/storage
    - deploy/operations
    - deploy/monitoring
    - deploy/apps
