---
# - name: Jellyfin Install
#   hosts: prod
#   become: true
#   vars: 
#   roles: 
#     - maintenance/update
#     - maintenance/clean

- name: Trigger Reboot 
  hosts: prod 
  become: true 
  # vars: 
  #   reboot: true
  roles: 
    - configure/common
