---
- name: Common Deployment Role
  hosts: all
  become: true
  become_user: root
  vars: 
    github_user: "meyersa"
    DEPLOY_TIMEZONE: "America/Detroit"
  roles: 
    - deploy/common

- name: Docker Deployment Role
  hosts: docker
  become: true
  roles: 
    - deploy/docker

- name: Kubernetes Deployment Roles
  hosts: kubernetes
  become: true
  roles: 
    - deploy/kubernetes

