---
- name: Common Deployment Playbook
  hosts: all
  become: true
  become_user: root
  vars: 
    github_user: "meyersa"
    DEPLOY_TIMEZONE: "America/Detroit"
    DEPLOY_ANSIBLE_USER: ansible
  roles: 
    - deploy
