- hosts: all
  become: true
  vars:
    created_username: ansible

  tasks:

    - name: Update apt and install required system packages
      apt:
        pkg:
          - git
          - dnsutil
          - netutil
        state: latest
        update_cache: true