---
- name: Cert Manager Setup
  tags: ["cert-manager"]
  block: 
  - name: Download Cert-Manager CRDs
    ansible.builtin.get_url:
      url: https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.crds.yaml
      dest: /var/manifests/cert-manager-crd.yaml
      force: true 

  - name: Apply Cert-Manager CRDs
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/cert-manager-crd.yaml

  - name: Add jetstack chart repo
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io

  - name: Deploy Cert-Manager helm chart
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: jetstack/cert-manager
      release_namespace: "{{ NAMESPACE }}"
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"
    retries: 3 
    
  - name: Copy Cert-Manager Config
    ansible.builtin.template:
      src: cert-manager.yml.j2
      dest: /var/manifests/cert-manager-config.yaml

  - name: Apply Cert-Manager Config
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/cert-manager-config.yaml
    register: result
    until: result.failed == false
    retries: 5
    delay: 60