---
- name: Cloudflared Setup
  tags: ["cloudflared"]
  block: 
  - name: Copy Cloudflared
    ansible.builtin.template:
      src: cloudflared.yml.j2
      dest: /var/manifests/cloudflared.yaml
  
  - name: Apply Cloudflared
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/cloudflared.yaml
      state: "{{ STATE }}"
