---
- name: Longhorn Setup
  tags: ["longhorn"]
  block: 
  - name: Add Longhorn chart repo
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io

  - name: Deploy Longhorn helm chart
    kubernetes.core.helm:
      name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: "{{ NAMESPACE }}"
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"
