---
- name: NameSpace
  ansible.builtin.set_fact:
    NAMESPACE: operations

- name: Create Operations Namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: "{{ NAMESPACE }}"
    kind: Namespace
    state: present

- import_tasks: cert-manager.yml

- import_tasks: traefik.yml