---
- name: Operations Deployment
  tags: ["operations"]
  block: 
  - name: NameSpace
    ansible.builtin.set_fact:
      NAMESPACE: operations

  - name: Create Operations Namespace
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      name: "{{ NAMESPACE }}"
      kind: Namespace
      state: present

  - import_tasks: cert-manager.yml

  - import_tasks: traefik.yml

  - import_tasks: longhorn.yml