- name: MinIO
  tags: ["minio"]
  vars:
    MINIO_DATA_DIR: "{{ DATA_DIR }}/minio"
  block:
    - name: Create MinIO network
      docker_network:
        name: minio

    - name: Create MinIO data directory
      file:
        path: "{{ MINIO_DATA_DIR }}"
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    - name: Run MinIO container
      docker_container:
        name: minio
        image: minio/minio:latest
        state: started
        restart_policy: unless-stopped
        command: server /data
        env:
          MINIO_ACCESS_KEY: "{{ MINIO_ACCESS_KEY }}"
          MINIO_SECRET_KEY: "{{ MINIO_SECRET_KEY }}"
        volumes:
          - "{{ MINIO_DATA_DIR }}:/data"
        networks:
          - name: minio
