- name: Clean host
  tags: ["clean"]
  block:
    - import_tasks: roles/util/tasks/webhook.yml
      vars: 
        message: "Cleaning..."
        status: "Info"

    - name: Run JournalCTL Vacuum
      ansible.builtin.command: journalctl --vacuum-size 10M

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
      retries: 3 
      
    - name: Remove packages from local cache 
      ansible.builtin.apt:
        autoclean: yes

    - name: Check if Docker is installed
      ansible.builtin.command: "docker --version"
      register: docker_check
      ignore_errors: yes

    - name: Run Docker System Prune
      when: docker_check.rc == 0
      ansible.builtin.command: docker system prune -f

    - import_tasks: roles/util/tasks/webhook.yml
      vars: 
        message: "Finished Cleaning"
        status: "Success"

  rescue:
    - import_tasks: roles/util/tasks/webhook.yml
      vars: 
        message: "Failed to clean"
        status: "Error"
