# https://www.reddit.com/r/ansible/comments/134oovg/task_working_but_failing_removing_old_kernels/
---
- name: Remove old kernels
  tags: ["kernel-clean"]
  block:
    - name: Get the list of installed kernels
      ansible.builtin.shell: "rpm -q kernel --qf '%{version}-%{release}\n' | sort -V"
      register: installed_kernels

    - name: Get the current running kernel
      ansible.builtin.command: "uname -r"
      register: current_kernel

    - name: Set the number of kernels to keep
      set_fact:
        kernels_to_keep: 3

    - name: Filter out the current and the latest kernels
      set_fact:
        old_kernels: "{{ installed_kernels.stdout_lines | difference([current_kernel.stdout]) | reverse | slice(kernels_to_keep)|list }}"

    - name: Remove old kernels
      ansible.builtin.yum:
        name: "kernel-{{ item }}"
        state: absent
      loop: "{{ old_kernels }}"
