{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of CPU time spent on non-idle modes (e.g., user, system) for each instance over the past 5 minutes. It provides insight into the CPU utilization, helping to understand how much of the CPU's capacity is being actively used compared to being idle.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / sum by(instance) (rate(node_cpu_seconds_total[5m])) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Alerts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{job=\"grafana\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of memory used by each instance, based on the total available memory and the available memory. It provides insight into the memory consumption, helping to understand how much memory is being utilized compared to the total available memory on the system.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (1 - (node_memory_MemAvailable_bytes{job=\"integrations/unix\"} / node_memory_MemTotal_bytes{job=\"integrations/unix\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "description": "This query counts the number of instances that are currently up (i.e., not in a down state) within the \"integrations/unix\" job. It helps track the availability of monitored instances, providing a snapshot of which instances are currently operational.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "up" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"integrations/unix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "This query calculates the average duration of probes (in milliseconds) over the past 5 minutes for each container. It helps assess the responsiveness of containers, highlighting any delays or performance issues.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (target_container) (\r\n  label_replace(avg_over_time(probe_duration_seconds[5m]), \"target_container\", \"$1\", \"target_container\", \"^/?(.*)$\")\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websites Down",
   "type": "stat",
   "description": "This query calculates the difference between the total number of probes and the successful ones. If the result is greater than zero, it indicates probe failures, suggesting potential issues with the monitored service or endpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success) - sum(probe_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of used disk space for each instance, specifically for the root filesystem (\"/\"). It compares the free space to the total disk space, providing insight into how much of the filesystem is utilized compared to the total available storage.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (100 - (node_filesystem_free_bytes{mountpoint=\"/\", job=\"integrations/unix\"} / node_filesystem_size_bytes{mountpoint=\"/\", job=\"integrations/unix\"} * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24 Uptime",
   "type": "timeseries",
   "description": "This query calculates the average success rate of probes over the past 24 hours for each container. It helps track the long-term reliability and uptime of containers, highlighting any persistent issues with specific containers.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (target_container) (\r\n  label_replace(avg_over_time(probe_success[24h]), \"target_container\", \"$1\", \"target_container\", \"^/?(.*)$\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websites Up",
   "type": "stat",
   "description": "This query counts the total number of successful probes. It indicates the number of times the monitored service or endpoint was successfully reached.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probe_success)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JournalCTL Percent Error",
   "type": "timeseries",
   "description": "This query calculates the total count of log entries containing the word \"critical\" for each instance within the \"journalctl\" job over the past 5 minutes. It helps monitor the frequency of critical system events or errors logged by each instance in a short time period.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * sum by(instance) (count_over_time({job=\"journalctl\"} |~ \"critical|err|severe|panic\" [5m]))\r\n/\r\nsum by(instance) (count_over_time({job=\"journalctl\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Logs Percent Error",
   "type": "timeseries",
   "description": "This query calculates the percentage of logs containing critical or error-related keywords (\"critical\", \"err\", \"severe\", \"panic\") out of the total logs for each instance within the \"docker\" job over the past 5 minutes. It helps assess the proportion of high-severity log entries compared to the overall log volume, indicating potential issues or critical events.",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (\r\n  sum by(instance) (count_over_time({job=\"docker\"} |~ \"critical|err|severe|panic\" [5m]))\r\n)\r\n/\r\nsum by(instance) (count_over_time({job=\"docker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSH Connection Status",
   "type": "timeseries",
   "description": "This query calculates the total number of SSH connections (closed, successful, and errors) in the past 5 minutes. It provides an overview of SSH activity, tracking session terminations, successful connections, and failed connection attempts, helping to monitor the health and reliability of SSH access.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "sum(changes(loki_process_custom_ssh_closed[5m]))",
     "legendFormat": "Closed"
    },
    {
     "expr": "sum(changes(loki_process_custom_ssh_error[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(changes(loki_process_custom_ssh_success[5m]))",
     "legendFormat": "Success"
    }
   ]
  }
 ]
}