---
- name: Longhorn Setup
  tags: ["longhorn"]
  block: 
  - name: Add Longhorn chart repo
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io
      
  # Only install on "server" nodes
  - name: Deploy Longhorn helm chart
    kubernetes.core.helm:
      name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: "{{ NAMESPACE }}"
      release_state: "{{ STATE }}"
      wait: true
      values:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - server
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"

  - name: Delete on remove Longhorn chart repo
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io
      repo_state: "{{ STATE }}"
    when: STATE == "absent"

  - name: Copy LongHorn StorageClass
    ansible.builtin.template:
      src: longhorn.yml.j2
      dest: /var/manifests/longhorn.yml
  
  - name: Apply LongHorn StorageClass
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/longhorn.yml
      state: "{{ STATE }}"