---
- name: Storage Deployment
  tags: ["storage"]
  when: KUBERNETES_MASTER is true
  block: 
  - name: storage
    ansible.builtin.set_fact:
      NAMESPACE: storage

  # Don't mess with storage namespaces due to persistent volumes
  - name: Create Storage Namespace
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      name: "{{ NAMESPACE }}"
      kind: Namespace

  - import_tasks: longhorn.yml

  - import_tasks: mongodb.yml

  - import_tasks: mariadb.yml

  - import_tasks: minio.yml