- name: MariaDB Setup (Simple Single Pod)
  tags: ["mariadb"]
  block:

  - name: Create MariaDB Secret
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: mariadb-root
          namespace: "{{ NAMESPACE }}"
        type: Opaque
        stringData:
          password: "{{ MARIADB_ROOT }}"
      state: "{{ STATE }}"

  - name: Copy MariaDB manifest
    ansible.builtin.template:
      src: mariadb.yml.j2
      dest: /var/manifests/mariadb.yml

  - name: Apply MariaDB StatefulSet + Service
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/mariadb.yml
      state: "{{ STATE }}"
