- name: Minio Setup (Single Node)
  tags: ["minio"]
  block:
  - name: Install Minio Client 
    ansible.builtin.apt:
      name:
        - mc
      state: present
      update_cache: true

  - name: Create MinIO Secret
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: minio-creds
          namespace: "{{ NAMESPACE }}"
        type: Opaque
        stringData:
          accesskey: "{{ MINIO_ACCESS_KEY }}"
          secretkey: "{{ MINIO_SECRET_KEY }}"
      state: "{{ STATE }}"

  - name: Copy MinIO manifest
    ansible.builtin.template:
      src: minio.yml.j2
      dest: /var/manifests/minio.yml

  - name: Apply MinIO Deployment
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/minio.yml
      state: "{{ STATE }}"