# Test configuration from inside of Kubernetes 
# kubectl run mongo-test --rm -it --image=mongo -- /bin/bash
# And then mongosh <connection-string>
---
- name: MongoDB Setup
  tags: ["mongodb"]
  block: 
  - name: Add MongoDB chart repo
    kubernetes.core.helm_repository:
      name: mongodb
      repo_url: https://mongodb.github.io/helm-charts
      repo_state: "{{ STATE }}"
      
  - name: Deploy MongoDB helm chart
    kubernetes.core.helm:
      name: community-operator
      chart_ref: mongodb/community-operator
      release_namespace: "{{ NAMESPACE }}"
      release_state: "{{ STATE }}"
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"

  - name: Copy MongoDB Config
    ansible.builtin.template:
      src: mongodb.yml.j2
      dest: /var/manifests/mongodb.yaml
  
  - name: Apply MongoDB Config
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/mongodb.yaml
      state: "{{ STATE }}"

  - name: Apply Mongo Operator Patch
    when: STATE == "present"
    block: 
    - name: Get Operator for Patch
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ NAMESPACE }}"
        name: mongodb-kubernetes-operator
      register: deployment_info

    - name: Extract current image for Patch
      set_fact:
        current_image: "{{ deployment_info.resources[0].spec.template.spec.containers[0].image }}"

    - name: Patch MongoDB Operator Deployment
      kubernetes.core.k8s:
        state: patched
        kind: Deployment
        api_version: apps/v1
        namespace: "{{ NAMESPACE }}"
        name: mongodb-kubernetes-operator
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: mongodb-kubernetes-operator
                    image: "{{ current_image }}"
                    resources:
                      requests:
                        cpu: "200m"
                        memory: "250Mi"
                      limits:
                        cpu: "500m"
                        memory: "750Mi"
        merge_type: merge
