- name: MongoDB Setup (Simple Single Pod)
  tags: ["mongodb"]
  block:

  - name: Create MongoDB Secret
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: mongodb-root
          namespace: "{{ NAMESPACE }}"
        type: Opaque
        stringData:
          password: "{{ MONGODB_ROOT }}"
      state: "{{ STATE }}"

  - name: Copy MongoDB manifest
    ansible.builtin.template:
      src: mongodb.yml.j2
      dest: /var/manifests/mongodb.yml

  - name: Apply MongoDB StatefulSet + Service
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/mongodb.yml
      state: "{{ STATE }}"