- name: Traefik Setup
  tags: ["traefik"]
  when: KUBERNETES_MASTER is true
  block: 
  - import_tasks: cert-manager.yml 
  
  - name: Download Traefik RBAC
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/traefik/traefik/v3.2/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
      dest: /var/manifests/traefik-rbac.yaml
      force: true 

  - name: Apply Traefik RBAC
    kubernetes.core.k8s:
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
      src: /var/manifests/traefik-rbac.yaml

  - name: Copy Config
    ansible.builtin.template:
      src: traefik.yml.j2
      dest: /var/manifests/traefik.yaml
  
  - name: Apply Traefik
    kubernetes.core.k8s:
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
      src: /var/manifests/traefik.yaml
      
  - name: Copy Config
    ansible.builtin.template:
      src: whoami.yml.j2
      dest: /var/manifests/whoami.yaml

  - name: Apply WhoAmI
    kubernetes.core.k8s:
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
      src: /var/manifests/whoami.yaml
