---
- name: Operations Deployment
  tags: ["operations"]
  when: KUBERNETES_MASTER is true
  block: 
  - name: NameSpace
    ansible.builtin.set_fact:
      NAMESPACE: operations

  - name: Create Operations Namespace
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      name: "{{ NAMESPACE }}"
      kind: Namespace

  - import_tasks: cert-manager.yml

  - import_tasks: traefik.yml

  - import_tasks: cloudflared.yml

  - import_tasks: argocd.yml