---
- name: Traefik Setup
  tags: ["traefik"]
  block: 
  - name: Add Traefik chart repo
    kubernetes.core.helm_repository:
      name: traefik
      repo_url: https://traefik.github.io/charts
      repo_state: "{{ STATE }}"
      
  - name: Copy Traefik Values
    ansible.builtin.template:
      src: traefik-values.yml.j2
      dest: /var/manifests/traefik-values.yaml

  - name: Deploy Traefik helm chart
    kubernetes.core.helm:
      name: traefik
      chart_ref: traefik/traefik
      release_namespace: "{{ NAMESPACE }}"
      values_files: /var/manifests/traefik-values.yaml
      release_state: "{{ STATE }}"
      wait: true
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"
    
  - name: Copy Traefik Middleware
    ansible.builtin.template:
      src: traefik-middleware.yml.j2
      dest: /var/manifests/traefik-middleware.yaml
  
  - name: Apply Traefik Middleware
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/traefik-middleware.yaml
      state: "{{ STATE }}"
