modules:
  http_2xx:
    prober: "http"
    timeout: "5s"
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200, 204, 301, 302, 308]
      follow_redirects: true
      preferred_ip_protocol: "ip4"
      headers: 
        User-Agent: "BlackBox-Alloy"
      enable_http2: false