---
- name: Add hosts
  tags: ["kube-hosts"]
  block:
    - name: Gather list of current play hosts
      set_fact:
        current_play_hosts: "{{ ansible_play_hosts }}"

    - name: Create list of host entries
      set_fact:
        host_entries: |
          {% for host in current_play_hosts %}
          {{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }} {{ host }}
          {% endfor %}

    - name: Backup existing /etc/hosts file
      copy:
        src: /etc/hosts
        dest: /etc/hosts.bak
        remote_src: yes
        backup: yes

    - name: Add current play hosts to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          # Added by Ansible
          {{ host_entries }}