- name: "Copy {{ NAME }} Config"
  ansible.builtin.template:
    src: web-app.yml.j2
    dest: "/var/manifests/{{ NAME }}.yaml"

- name: "Apply {{ NAME }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    src: "/var/manifests/{{ NAME }}.yaml"
    state: "{{ STATE }}"
