---
- name: Deploy Docker Applications
  tags: ["apps"]
  block:
  - name: Deploy whoami
    include_tasks: _deploy_app.yml
    when: ENVIRONMENT == "dev"
    vars: 
      app: "whoami"
      containers: 
        - name: whoami
          image: traefik/whoami
          url: whoami.{{ FRONTEND_DOMAIN}}
          port: 80

  - name: Deploy meyersa
    include_tasks: _deploy_app.yml
    vars:
      app: "meyersa"
      containers:
        - name: meyersa
          image: ghcr.io/meyersa/new-web:latest
          url: "{{ FRONTEND_DOMAIN }}"
          port: 3000

  - name: Deploy TruthRadar
    include_tasks: _deploy_app.yml
    vars:
      app: "truthradar"
      containers:
        - name: truthradar
          image: ghcr.io/meyersa/truthradar:latest
          url: "truthradar.{{ FRONTEND_DOMAIN }}"
          port: 5000
          dbs:
            - mongodb
          envs: 
            - "OPENAI_API_KEY: {{ TR_OA_KEY }}"
            - "API_KEY: {{ TR_KEY }}"
            - "MONGO_DB: {{ TR_MONGO_DB }}"
            - "MONGO_URL: {{ TR_MONGO_DB }}"

  - name: Deploy CampusGrows
    include_tasks: _deploy_app.yml
    vars: 
      app: "campusgrows"
      containers: 
        - name: campusgrows
          image: ghcr.io/meyersa/campusgrows:latest
          url: "campusgrows.{{ FRONTEND_DOMAIN }}"
          port: 80
        
  # - name: Deploy MaxMind
  #   include_tasks: _deploy_app.yml
  #   vars: 
  #     app: "maxmind"
  #     containers: 
  #       - name: maxmind
  #         image: 

  # Needs Storage
  # ShodanETL
  # Travel
  # CloudSCT
  # IP