---
- import_tasks: deploy-app.yml
  vars:
    NAME: whoami
    PORT: 80
    DOMAIN: lb.meyerstk.com
    IMAGE: containous/whoami

- import_tasks: deploy-app.yml
  vars:
    NAME: meyersa
    PORT: 3000
    DOMAIN: meyersa.meyerstk.com
    IMAGE: ghcr.io/meyersa/new-web:latest

- import_tasks: deploy-app.yml
  vars:
    NAME: dmaxmind
    PORT: 8080
    DOMAIN: dmaxmind.meyerstk.com
    IMAGE: observabilitystack/geoip-api      
    API: true