---
- name: Deploy Docker Applications
  tags: ["apps"]
  block:
  - name: Deploy whoami
    include_tasks: roles/util/tasks/deploy_app.yml
    when: ENVIRONMENT == "dev"
    tags: ["whoami"]
    vars: 
      app: "whoami"
      containers: 
        - name: frontend
          image: traefik/whoami
          noindex: true
          url: whoami.{{ FRONTEND_DOMAIN}}
          port: 80

  - name: Deploy meyersa
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["meyersa"]
    vars:
      app: "meyersa"
      containers:
        - name: frontend
          image: ghcr.io/meyersa/new-web:latest
          url: "{{ FRONTEND_DOMAIN }}"
          port: 3000

  - name: Deploy CampusGrows
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["campusgrows"]
    vars: 
      app: "campusgrows"
      containers: 
        - name: frontend
          image: ghcr.io/meyersa/campusgrows:latest
          url: "campusgrows.{{ FRONTEND_DOMAIN }}"
          port: 80

  - name: Deploy MaxMind
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["maxmind"]
    vars: 
      app: "maxmind"
      containers: 
        - name: api
          image: observabilitystack/geoip-api:latest
          url: "maxmind.{{ BACKEND_DOMAIN }}"
          mon_path: "/1.1.1.1"
          port: 8080
          api: true

  - name: Deploy TruthRadar
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["truthradar"]
    vars:
      app: "truthradar"
      mongo_user: "{{ TR_MONGO_USER }}"
      mongo_pass: "{{ TR_MONGO_PASS }}"
      mongo_db: "{{ TR_MONGO_DB }}"
      containers:
        - name: frontend
          image: ghcr.io/meyersa/truthradar:latest
          url: "truthradar.{{ FRONTEND_DOMAIN }}"
          port: 5000
          noindex: true
          dbs:
            - mongodb
          envs: 
            - "OPENAI_API_KEY: {{ TR_OA_KEY }}"
            - "API_KEY: {{ TR_KEY }}"
            - "MONGO_DB: {{ TR_MONGO_DB }}"
            - "MONGO_URL: {{ TR_MONGO_URL }}"
        - name: api 
          image: ghcr.io/meyersa/truthradar-api:latest
          url: "truthradar.{{ FRONTEND_DOMAIN }}"
          path: "/predict"
          port: 8000
          noindex: true
          multiplier: 8
          envs: 
            - "MODEL_LINK: {{ TR_API_MODEL_LINK }}"
            - "VECTORIZER_LINK: {{ TR_API_VECTORIZER_LINK }}"
            - "API_KEY: {{ TR_API_API_KEY }}"

  # - name: ShodanETL
  #   include_tasks: roles/util/tasks/deploy_app.yml
  #   tags: ["shodanetl"]
  #   vars: 
  #     app: "shodanetl"
  #     mongo_user: "{{ SE_MONGO_USER }}"
  #     mongo_pass: "{{ SE_MONGO_PASS }}"
  #     mongo_db: "{{ SE_MONGO_DB }}"
  #     containers: 
  #       - name: frontend
  #         image: ghcr.io/meyersa/shodan_display:latest
  #         url: "shodanetl.{{ FRONTEND_DOMAIN }}"
  #         noindex: true
  #         port: 3000
  #         dbs: 
  #           - mongodb
  #         envs: 
  #           - "MONGO_DB: {{ SE_MONGO_DB }}"
  #           - "MONGO_URL: {{ SE_MONGO_URL }}"
        # - name: backend
        #   image: ghcr.io/meyersa/shodan_producer:latest
        #   dbs: 
        #     - mongodb
        #   envs: 
        #     - "MONGO_DB: {{ SE_MONGO_DB }}"
        #     - "MONGO_URL: {{ SE_MONGO_URL }}"
        #     - "SHODAN_API_KEY: {{SE_SHODAN_API_KEY}}"
        #     - "SHODAN_QUERY: {{SE_SHODAN_QUERY}}"
        #     - "CROWDSEC_LAPI_URL: {{SE_CROWDSEC_LAPI_URL}}"
        #     - "CROWDSEC_LAPI_KEY: {{SE_CROWDSEC_LAPI_KEY}}"
        #     - "MAXMIND_API_URL: {{SE_MAXMIND_API_URL}}"
            
  - name: CloudSCT
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["cloudsct"]
    vars: 
      app: "cloudsct"
      mongo_user: "{{ CS_MONGO_USER }}"
      mongo_pass: "{{ CS_MONGO_PASS }}"
      mongo_db: "{{ CS_MONGO_DB }}"
      containers: 
        - name: frontend
          image: ghcr.io/meyersa/cloudsct-frontend:latest
          url: "cloudsct.{{ FRONTEND_DOMAIN }}"
          noindex: true
          port: 3000
          dbs: 
            - mongodb
          envs: 
            - "MONGO_DB: {{ CS_MONGO_DB }}"
            - "MONGO_URL: {{ CS_MONGO_URL }}"
        - name: backend
          image: ghcr.io/meyersa/cloudsct-backend:latest
          dbs: 
            - mongodb
          envs: 
            - "MONGO_DB: {{ CS_MONGO_DB }}"
            - "MONGO_URL: {{ CS_MONGO_URL }}"
            
  - name: Travel
    include_tasks: roles/util/tasks/deploy_app.yml
    tags: ["travel"]
    vars: 
      app: "travel"
      mongo_user: "{{ TL_MONGO_USER }}"
      mongo_pass: "{{ TL_MONGO_PASS }}"
      mongo_db: "{{ TL_MONGO_DB }}"
      containers: 
        - name: frontend
          image: ghcr.io/meyersa/travel:latest
          url: "travel.{{ FRONTEND_DOMAIN }}"
          noindex: true
          port: 3000
          dbs: 
            - mongodb
          envs: 
            - "MONGO_DB: {{ TL_MONGO_DB }}"
            - "MONGO_URL: {{ TL_MONGO_URL }}"
            - "SERVER_KEY: {{ TL_SERVER_KEY }}"
            - "OPENAI_KEY: {{ TL_OPENAI_KEY }}"

  # Needs Storage
  # IP