---
- name: MongoDB Setup
  tags: ["mongodb"]
  block: 
  - name: Add MongoDB chart repo
    kubernetes.core.helm_repository:
      name: mongodb
      repo_url: https://mongodb.github.io/helm-charts

  - name: Deploy MongoDB helm chart
    kubernetes.core.helm:
      name: community-operator
      chart_ref: mongodb/community-operator
      release_namespace: "default"
    environment: 
      KUBECONFIG: "{{ KUBECONFIG }}"

  - name: Copy MongoDB Config
    ansible.builtin.template:
      src: mongodb.yml.j2
      dest: /var/manifests/mongodb.yaml
  
  - name: Apply MongoDB Config
    kubernetes.core.k8s:
      kubeconfig: "{{ KUBECONFIG }}"
      src: /var/manifests/mongodb.yaml