apiVersion: 1
datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    jsonData:
      prometheusType: Mimir
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
