- name: Configure host
  tags: ["config"]
  block:
  - import_tasks: ../../util/webhook.yml
    vars: 
      status: "Info"
      message: "Configuring common..."

  # Create user account
  - import_tasks: access.yml

  # Install Packages
  - import_tasks: apt.yml

  - name: Create directory for GPG keys
    tags: ["keyring"]
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  # Set Hostname 
  - import_tasks: hostname.yml

  # Configure UFW
  - import_tasks: ufw-basic.yml

  # Install Crowdsec
  - import_tasks: crowdsec-bouncer.yml

  # Install Warp
  - import_tasks: warp.yml

  # DDNS
  - import_tasks: ddclient.yml 

  # Configure Monitoring
  - import_tasks: grafana-alloy.yml 

  # Disable Swap
  - import_tasks: swap.yml

  # Reboot Host
  - import_tasks: ../../util/reboot.yml
    when: reboot is defined and reboot

  - import_tasks: ../../util/webhook.yml
    vars: 
      status: "Success"
      message: "Configured host"

  rescue: 
    - import_tasks: ../../util/webhook.yml
      vars: 
        status: "Error"
        message: "Failed to configure common on host"
