---
- name: Install Apt Packages
  tags: ["apt"]
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - python3
          - git
          - dnsutils
          - net-tools
          - curl
          - wget
          - htop
          - nano
          - unzip
          - nodejs
          - npm
          - apt-transport-https
          - ca-certificates
          - gnupg
          - software-properties-common
          - debian-archive-keyring
        state: latest
        update_cache: true
