# Create user account
- import_tasks: access.yml

# Update host
- import_tasks: ../../util/update.yml

# Install Packages
- import_tasks: apt.yml

- name: Create directory for GPG keys
  tags: ["keyring"]
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

# Set Hostname 
- name: Set a hostname specifying strategy
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

# Set TimeZone
- import_tasks: timezone.yml

# Configure UFW
- import_tasks: ufw-basic.yml

# Install Crowdsec
- import_tasks: crowdsec-bouncer.yml

# DDNS
- import_tasks: ddclient.yml 

# Configure Monitoring
- import_tasks: grafana-alloy.yml 

# Disable Swap
- import_tasks: swap.yml

# Reboot Host
# - import_tasks: ../../util/reboot.yml

- name: Send a message to the Discord channel
  community.general.discord:
    webhook_id: "{{ DEPLOY_WEBHOOK_ID }}"
    webhook_token: "{{ DEPLOY_WEBHOOK_TOKEN }}"
    content: "Host {{ inventory_hostname }} has been deployed"
