{
 "title": "Database Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "MongoDB Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"query\"}[5m])\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Deletes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"delete\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Documents",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_objects{database!~\"admin|config|local\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 }, "options": { "content": "Total rows" } },
  {
   "title": "MongoDB Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"update\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 }, "options": { "content": "Total Updates" } },
  {
   "title": "MongoDB Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{database!~\"admin|local|config\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 }, "options": { "content": "Total Tables" } },
  {
   "title": "MongoDB Inserts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"insert\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 }, "options": { "content": "Total Inserts" } }
 ]
}