{
 "title": "Log Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Docker Logs (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"docker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Lines per Hour",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1h]) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Logs (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"} [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Logs (Error)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"docker\"} |= `error` [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Logs (Error)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"} |= `error` [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Logs (Critical)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"docker\"} |= `critical` [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Logs (Critical)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"} |= `critical` [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}