{
 "title": "System Stats",
 "description": "Overview of systems being monitored",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / sum by(instance) (rate(node_cpu_seconds_total[5m])) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) ((node_time_seconds{job=\"integrations/unix\"} - node_boot_time_seconds{job=\"integrations/unix\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (node_processes_pids{job=\"integrations/unix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_io_waiting_seconds_total{job=\"integrations/unix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (1 - (node_memory_MemAvailable_bytes{job=\"integrations/unix\"} / node_memory_MemTotal_bytes{job=\"integrations/unix\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{job=\"integrations/unix\", device!~\"lo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{job=\"integrations/unix\", device!~\"lo\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_memory_waiting_seconds_total{job=\"integrations/unix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (100 - (node_filesystem_free_bytes{mountpoint=\"/\", job=\"integrations/unix\"} / node_filesystem_size_bytes{mountpoint=\"/\", job=\"integrations/unix\"} * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_read_bytes_total{job=\"integrations/unix\"}[5m])) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_written_bytes_total{job=\"integrations/unix\"}[5m])) / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_cpu_waiting_seconds_total{job=\"integrations/unix\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}