---
- name: Install Apt Packages
  tags: ["apt"]
  block:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - git
          - dnsutils
          - net-tools
          - curl
          - wget
          - htop
          - nano
          - unzip
          - nodejs
          - npm
        state: latest
        update_cache: true
