# TODO: Configure Crowdsec
---
- name: Install Crowdsec Bouncer
  tags: ["crowdsec"]
  block:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - crowdsec-firewall-bouncer-iptables
