{
 "title": "Security Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SSH Map",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(connecting_ip, geoip_location_latitude, geoip_location_longitude) (count_over_time(loki_process_custom_ssh_success{maxmind=\"true\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(connecting_ip, geoip_location_latitude, geoip_location_longitude) (count_over_time(loki_process_custom_ssh_closed{maxmind=\"true\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH Connection Status",
   "type": "timeseries",
   "description": "This query calculates the total number of SSH connections (closed, successful, and errors) in the past 5 minutes. It provides an overview of SSH activity, tracking session terminations, successful connections, and failed connection attempts, helping to monitor the health and reliability of SSH access.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(changes(loki_process_custom_ssh_closed[5m]))",
     "legendFormat": "Closed"
    },
    {
     "expr": "sum(changes(loki_process_custom_ssh_error[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(changes(loki_process_custom_ssh_success[5m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Crowdsec Alerts by Reason",
   "type": "timeseries",
   "description": "This query returns the top 5 most common alert reasons from the cs_alerts metric. It helps identify the most frequent causes of alerts, providing insight into recurring issues or conditions that are triggering alerts in the system.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by(reason) (cs_alerts))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top SSH Failed Users",
   "type": "timeseries",
   "description": "This query returns the top 5 users who have the highest number of closed SSH connections, based on the loki_process_custom_ssh_closed metric. It helps identify which users are closing the most SSH connections, providing insight into user activity or potential issues related to specific user sessions.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "topk(5, sum by(connecting_user) (loki_process_custom_ssh_closed))",
     "legendFormat": "{{connecting_user}}"
    }
   ]
  },
  {
   "title": "CrowdSec Top Parsers",
   "type": "timeseries",
   "description": "This query returns the top 5 buckets with the highest number of poured events, based on the cs_bucket_poured_total metric. It helps identify the buckets that are most active in terms of poured events, providing insights into data flow or usage patterns within the system.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "topk(5, sum by(name) (cs_bucket_poured_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top SSH Failed IPs",
   "type": "timeseries",
   "description": "This query returns the top 5 IP addresses with the highest number of closed SSH connections, based on the loki_process_custom_ssh_closed metric. It helps identify which IPs are responsible for the most SSH session terminations, which can indicate user activity patterns or potential security concerns related to specific IP addresses.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, sum by(connecting_ip) (loki_process_custom_ssh_closed))",
     "legendFormat": "{{connecting_ip}}"
    }
   ]
  },
  {
   "title": "CrowdSec Top Overflows",
   "type": "timeseries",
   "description": "This query returns the top 5 buckets with the highest number of overflow events, based on the cs_bucket_overflowed_total metric. It helps identify which buckets are experiencing the most overflows, potentially indicating issues with capacity or resource management in the system.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, sum by(name) (cs_bucket_overflowed_total))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}