{
 "title": "Web Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "This query calculates the average duration of probes (in milliseconds) over the past 5 minutes for each container. It helps assess the responsiveness of containers, highlighting any delays or performance issues.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (target_container) (\r\n  label_replace(avg_over_time(probe_duration_seconds[5m]), \"target_container\", \"$1\", \"target_container\", \"^/?(.*)$\")\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "This query counts the total number of successful probes. It indicates the number of times the monitored service or endpoint was successfully reached.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probe_success)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "This query calculates the difference between the total number of probes and the successful ones. If the result is greater than zero, it indicates probe failures, suggesting potential issues with the monitored service or endpoint.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success) - sum(probe_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entrypoint Request Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of HTTP requests for each entrypoint in Traefik over the past 5 minutes, grouped by entrypoint.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "stat",
   "description": "This query calculates the percentage of successful (2xx) HTTP requests for each Traefik-managed service over the past 5 minutes. It provides an overview of the reliability of the service by comparing the successful requests to the total requests.",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_requests_total{code=~\"2..\"}[5m]) * 100)) / sum(rate(traefik_service_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "description": "This query calculates the percentage of HTTP requests that resulted in errors (4xx and 5xx status codes) for each Traefik-managed service over the past 5 minutes. It helps identify issues with the service's availability or client interactions.",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_requests_total{code!~\"2..\"}[5m]) * 100)) / sum(rate(traefik_service_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services by Requests",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of HTTP requests for each Traefik-managed service over the past 5 minutes. It focuses on the requests processed by each service, helping identify request load per service.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (\r\n  label_replace(rate(traefik_service_requests_total[5m]), \"service\", \"$1\", \"service\", \"^(.*)@.*$\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Response Time",
   "type": "timeseries",
   "description": "This query calculates the average request duration in milliseconds for each Traefik-managed service over the past 5 minutes, based on the sum of request durations and the count of requests.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(service) (\r\n  label_replace(\r\n    rate(traefik_service_request_duration_seconds_sum[5m]) / rate(traefik_service_request_duration_seconds_count[5m]) * 1000, \r\n    \"service\", \r\n    \"$1\", \r\n    \"service\", \r\n    \"(.*)@docker\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "description": "This query calculates the per-minute sum of successful (2xx) and redirected (3xx) HTTP requests for Traefik-managed services over the past 5 minutes.",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"2..|3..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "stat",
   "description": "This query calculates the total number of HTTP requests that resulted in errors (4xx and 5xx status codes) for each Traefik-managed service over the past 5 minutes. It helps track service failures or issues with client requests.",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code!~\"2..|3..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request Size per Entrypoint",
   "type": "timeseries",
   "description": "This query calculates the average size of HTTP requests (in bytes) per entrypoint in Traefik over the past 5 minutes, by dividing the total request bytes by the total request count for each entrypoint.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_requests_bytes_total[5m])) / sum by(entrypoint) (rate(traefik_entrypoint_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1hr Uptime",
   "type": "timeseries",
   "description": "This query calculates the average success rate of probes over the past 5 minutes for each container. It helps monitor the health and availability of individual containers, identifying any potential issues with specific containers.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (target_container) (\r\n  label_replace(avg_over_time(probe_success[5m]), \"target_container\", \"$1\", \"target_container\", \"^/?(.*)$\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of HTTP requests for each status code (e.g., 2xx, 3xx, 4xx, 5xx) across all Traefik-managed services over the past 5 minutes. It helps monitor the distribution of request outcomes, providing insight into the success, redirection, or error rates.",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_service_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Size per Entrypoint",
   "type": "timeseries",
   "description": "This query calculates the average response size (in bytes) per HTTP request for each entrypoint in Traefik over the past 5 minutes, by dividing the total response bytes by the total request count for each entrypoint.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_responses_bytes_total[5m])) / sum by(entrypoint) (rate(traefik_entrypoint_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24 Uptime",
   "type": "timeseries",
   "description": "This query calculates the average success rate of probes over the past 24 hours for each container. It helps track the long-term reliability and uptime of containers, highlighting any persistent issues with specific containers.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (target_container) (\r\n  label_replace(avg_over_time(probe_success[24h]), \"target_container\", \"$1\", \"target_container\", \"^/?(.*)$\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "description": "This query calculates the total number of open connections for each entrypoint in Traefik. It helps monitor the connection load per entrypoint, indicating potential bottlenecks or high traffic.",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "sum by(entrypoint) (traefik_open_connections)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}