---
- hosts: all
  become: true
  vars:
    created_username: ansible

  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - git
          - dnsutils
          - net-tools
          - curl
          - wget
          - htop
          - nano
          - unzip
          - nodejs
          - npm
        state: latest
        update_cache: true

    - name: Install timezone packages
      apt: 
        pkg: 
          - tzdata 
          - ntp
        state: latest
        update_cache: true 

    - name: Set the timezone to America/Detroit
      timezone:
        name: America/Detroit

    - name: Configure NTP server
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server '
        line: 'server time.nist.gov'
        state: present
        backup: yes

    - name: Ensure NTP service is enabled and started
      service:
        name: ntp
        state: started
        enabled: yes