---
- name: Install Helm
  tags: ["helm"]
  block:
    - name: Add Helm's official GPG key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        keyring: /etc/apt/keyrings/helm.gpg
        state: present

    - name: Get DEB architecture
      command: dpkg --print-architecture
      register: deb_architecture

    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
        filename: helm-stable-debian
        state: present

    - name: Install Helm
      ansible.builtin.apt:
        name:
          - helm
        state: present
        update_cache: true